Repository Lu1z-Gust4v0/Fup-Final_Project, pull requests merged in 2022-06, with the labels that each got.

#46 19 allow user to input a play file
  src/args_parser.py
  src/check_moves.py
  src/checkers.py
  src/frontend.py
  src/helper_functions.py
  src/read_files.py
  sudoku.py
Labels: bug, documentation, Story

#48 13 iteractive mode
  arq_01_cfg.txt
  arq_01_jog.txt
  src/args_parser.py
  src/batch_mode.py
  src/check_moves.py
  src/checkers.py
  src/frontend.py
  src/helper_functions.py
  src/interactive_mode.py
  src/read_files.py
  sudoku.py
  teste.txt
Labels: bug, Story

#56 51 better way to handle erros2
  .github/workflows/python-package.yml
  src/batch_mode.py
  src/checkers.py
  src/display.py
  src/interactive_mode.py
  src/parsers.py
  src/populate.py
  sudoku.py
Labels: Story
